upgrade:rpc_context-module
apache/dubbo-samples pull request #1062
Opened 2024-03-14 10:05 UTC by Rawven

update jdk17 and springboot3, replace spring+xml  to springboot.

2024-03-14 10:06 UTC, Rawven commented
I have tested it locally

2024-03-18 02:45 UTC, chickenlj requested changes

2024-03-18 02:45 UTC, chickenlj commented on 2-advanced/dubbo-samples-rpccontext/pom.xml
> +
Please reference the pom.xml configuration in https://github.com/apache/dubbo-samples/blob/master/2-advanced/dubbo-samples-mock/pom.xml

2024-03-18 02:45 UTC, chickenlj commented on 2-advanced/dubbo-samples-rpccontext/pom.xml
> +
https://github.com/apache/dubbo-samples/blob/master/2-advanced/dubbo-samples-mock/dubbo-samples-mock-provider/pom.xml

2024-03-18 03:56 UTC, Rawven commented
I have fix it，please take a look@chickenlj

2024-03-18 04:13 UTC, merged