update version in dubbo-samples-validation
apache/dubbo-samples pull request #1066
Opened 2024-03-15 12:29 UTC by mming404

update the jdk version to 17 ,dubbo version to 3.2.*,use springboot replace spring.

2024-03-18 03:03 UTC, chickenlj requested changes

2024-03-18 03:03 UTC, chickenlj commented on 2-advanced/dubbo-samples-validation/pom.xml
> +            </exclusions>
One small issue, please use the dependency listed here instead https://github.com/apache/dubbo-samples/blob/master/2-advanced/dubbo-samples-mock/dubbo-samples-mock-provider/pom.xml#L47

2024-03-18 15:40 UTC, chickenlj approved these changes
LGTM.

2024-03-19 03:38 UTC, mming404 commented
can you merge it?please @chickenlj

2024-03-22 08:18 UTC, chickenlj requested changes

2024-03-22 08:18 UTC, chickenlj commented on 2-advanced/dubbo-samples-validation/src/test/java/org/apache/dubbo/samples/validation/ValidationServiceIT.java
> +    @DubboReference(url = "dubbo://localhost:20880")
`@DubboReference` would be ok, no `url` parameter needed.

2024-03-22 08:18 UTC, chickenlj commented on 2-advanced/dubbo-samples-validation/src/main/resources/application.yml
> +        validation: true
Please set `registry` here and change case-configuration.yml accordingly by referencing the following demo:
https://github.com/apache/dubbo-samples/tree/master/2-advanced/dubbo-samples-mock

2024-03-24 02:57 UTC, chickenlj approved these changes
Well done.

2024-03-24 02:57 UTC, merged