Dubbo samples mesh k8s: add envoy healthChecks
apache/dubbo-samples pull request #482
Opened 2022-07-16 06:15 UTC by conghuhu

feat: add envoy healthChecks to dubbo-samples-mesh-k8s

2022-07-18 03:47 UTC, CrazyHZM requested changes

2022-07-18 03:47 UTC, CrazyHZM commented on dubbo-samples-mesh-k8s/dubbo-samples-mesh-consumer/pom.xml
> +        <dubbo.version>3.0.7</dubbo.version>
Don't change this version.

2022-07-18 03:47 UTC, CrazyHZM commented on dubbo-samples-mesh-k8s/dubbo-samples-mesh-consumer/pom.xml
> +            <!--            <version>3.1.0-SNAPSHOT</version>-->
Remove useless code.

2022-07-18 03:47 UTC, CrazyHZM commented on dubbo-samples-mesh-k8s/dubbo-samples-mesh-consumer/src/main/java/org/apache/dubbo/samples/ConsumerBootstrap.java
> +        }
Don't loop endlessly.

2022-07-18 03:47 UTC, CrazyHZM commented on dubbo-samples-mesh-k8s/dubbo-samples-mesh-consumer/src/main/java/org/apache/dubbo/samples/action/GreetingServiceConsumer.java
> +//    @DubboReference(version = "1.0.0", providedBy = "dubbo-samples-mesh-provider", url = "tri://localhost:50052")
Remove useless code.

2022-07-18 03:47 UTC, CrazyHZM commented on dubbo-samples-mesh-k8s/dubbo-samples-mesh-provider/pom.xml
> +        <grpc.version>1.31.1</grpc.version>
Don't change this version.

2022-07-18 03:47 UTC, CrazyHZM commented on dubbo-samples-mesh-k8s/dubbo-samples-mesh-consumer/pom.xml
> +        <grpc.version>1.31.1</grpc.version>
Don't change this version.

2022-07-19 09:01 UTC, chickenlj commented
Please submit followup patches to fix the above minor issues.

2022-07-19 09:01 UTC, merged