add triple benchmark
apache/dubbo-samples pull request #514
Opened 2022-09-02 10:58 UTC by owen200008

add triple benchmark

2022-09-03 05:48 UTC, AlbumenJ requested changes

2022-09-03 05:48 UTC, AlbumenJ commented on dubbo-samples-triple/src/main/java/org/apache/dubbo/sample/tri/GrpcServers.java
> +package org.apache.dubbo.sample.tri;
Add asf license header

2022-09-03 05:48 UTC, AlbumenJ commented on dubbo-samples-triple/src/main/java/org/apache/dubbo/sample/tri/GrpcServers.java
> + * @alter_date
remove these tags pls

2022-09-06 06:11 UTC, owen200008 commented
https://github.com/apache/dubbo-samples/pull/516

2022-09-06 06:11 UTC, closed without merging