add tri samples
apache/dubbo-samples pull request #831
Opened 2023-04-26 14:30 UTC by icodening

simplify the samples of tri stub

2023-04-27 09:15 UTC, AlbumenJ requested changes

2023-04-27 09:15 UTC, AlbumenJ commented on 1-basic/dubbo-samples-triple-unary/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
Please add ASF license header

2023-04-27 11:01 UTC, icodening commented on 1-basic/dubbo-samples-triple-unary/pom.xml
> +<project xmlns="http://maven.apache.org/POM/4.0.0"
OK

2023-04-28 03:02 UTC, EarthChen approved these changes
LGTM

2023-04-28 03:03 UTC, merged